# These are supported funding model platforms

github: [soranoo]
buy_me_a_coffee: ['https://www.buymeacoffee.com/soranoo']
cryptocurrency_erc20: ['0x1150FCB0B9F6c59D87ABE1aC656b5A4cDB7e0dE1']
cryptocurrency_bsc: ['0x1150FCB0B9F6c59D87ABE1aC656b5A4cDB7e0dE1']
cryptocurrency_polygon: ['0x1150FCB0B9F6c59D87ABE1aC656b5A4cDB7e0dE1']
